"""
Router-R1 inspired Multi-Round Agentic Router for InferRoute.

Orchestrates multi-round reasoning:
1. Generates an initial draft response from a cheap local model.
2. Checks the quality of the draft using OutputValidator.
3. If validation fails, escalates the draft + validation errors to a cloud model to correct and finalize.
"""
import time
import logging
from typing import Any, Callable, Coroutine

logger = logging.getLogger("inferroute.agentic_router")


class AgenticRouter:
    async def run_agentic_flow(
        self,
        req: dict[str, Any],
        local_backend: str,
        cloud_backend: str,
        invoke_adapter_fn: Callable[[str, dict[str, Any]], Coroutine[Any, Any, dict[str, Any]]],
        validate_fn: Callable[[str, str], float],
        acceptance_threshold: float = 0.8
    ) -> dict[str, Any]:
        """
        Executes the multi-round agentic loop.
        """
        logger.info(f"[Router-R1] Round 1: Generating draft using local backend '{local_backend}'")
        
        # Invoke local backend to get draft
        start_time = time.time()
        try:
            draft_resp = await invoke_adapter_fn(local_backend, req)
            draft_text = draft_resp.get("choices", [{}])[0].get("message", {}).get("content", "")
        except Exception as e:
            logger.warning(f"[Router-R1] Round 1 draft generation failed: {e}. Escalating immediately to cloud.")
            return await invoke_adapter_fn(cloud_backend, req)

        # Round 2: Validate local draft
        score = validate_fn(req.get("messages", [])[-1].get("content", ""), draft_text)
        logger.info(f"[Router-R1] Draft validation score: {score:.3f} (threshold={acceptance_threshold:.3f})")
        
        if score >= acceptance_threshold:
            logger.info(f"[Router-R1] Local draft meets criteria! Returning local response.")
            draft_resp["choices"][0]["message"]["content"] = (
                f"<think>\nDraft generated by {local_backend}. Validation Score: {score:.2f} (PASS).\n</think>\n"
                + draft_text
            )
            return draft_resp

        # Round 3: Escalation and correction via cloud backend
        logger.info(f"[Router-R1] Local draft failed validation. Escalating correction to cloud backend '{cloud_backend}'")
        
        # Build correction prompt
        original_prompt = req["messages"][-1]["content"]
        correction_system_msg = (
            "You are a correction assistant. The user wants to solve the prompt below. "
            "A draft answer was generated but failed validation checks. "
            "Identify the errors in the draft, correct them, and output the perfect final response."
        )
        
        correction_messages = [
            {"role": "system", "content": correction_system_msg},
            {"role": "user", "content": f"Original Prompt: {original_prompt}\n\nDraft Answer: {draft_text}\n\nValidation Score: {score:.2f} (FAIL). Please correct the draft and provide the final answer."}
        ]
        
        # Copy request payload and swap messages
        cloud_req = req.copy()
        cloud_req["messages"] = correction_messages
        
        try:
            cloud_resp = await invoke_adapter_fn(cloud_backend, cloud_req)
            cloud_text = cloud_resp.get("choices", [{}])[0].get("message", {}).get("content", "")
            
            # Prepend reasoning thinking tags showing the multi-round process
            cloud_resp["choices"][0]["message"]["content"] = (
                f"<think>\nRound 1: Local draft by {local_backend} failed validation (Score: {score:.2f}).\n"
                f"Round 2: Escalated to {cloud_backend} for correction and validation check.\n</think>\n"
                + cloud_text
            )
            return cloud_resp
        except Exception as e:
            logger.error(f"[Router-R1] Cloud correction escalation failed: {e}")
            # If cloud correction fails, return draft as fail-safe fallback
            return draft_resp


agentic_router = AgenticRouter()
