import re

def generate_mock_reply(prompt: str, provider: str) -> str:
    """Generates context-aware, highly realistic responses for Simulation Mode."""
    prompt_clean = prompt.lower().strip()
    
    # 1. Repetitive loop trigger (for testing speculative quality validation!)
    if "loop" in prompt_clean or "repeat" in prompt_clean or "spam" in prompt_clean:
        return "hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello"

    # 2. Greetings
    if re.search(r"\b(hello|hi|hey|nihao|你好|哈喽)\b", prompt_clean):
        return (
            f"Hello there! I am a simulated {provider.upper()} model running in InferRoute's offline sandbox. "
            f"How can I assist you today? Feel free to ask me questions, test code examples, or type 'loop' to trigger a validation failure!"
        )

    # 3. Math equations / calculations
    if "2" in prompt_clean and ("=" in prompt_clean or "+" in prompt_clean or "equal" in prompt_clean):
        return (
            f"Mathematically, 2 + 2 = 4 (or 2 = 2 is true). This demonstrates basic arithmetic equivalence. "
            f"Since this is a simple query, InferRoute routed it to the local {provider} instance, costing you absolutely nothing ($0.00)."
        )

    # 4. Code requests
    if "code" in prompt_clean or "sort" in prompt_clean or "python" in prompt_clean or "javascript" in prompt_clean:
        return (
            "Here is a classic Python implementation of the Quick Sort algorithm:\n\n"
            "```python\n"
            "def quick_sort(arr):\n"
            "    if len(arr) <= 1:\n"
            "        return arr\n"
            "    pivot = arr[len(arr) // 2]\n"
            "    left = [x for x in arr if x < pivot]\n"
            "    middle = [x for x in arr if x == pivot]\n"
            "    right = [x for x in arr if x > pivot]\n"
            "    return quick_sort(left) + middle + quick_sort(right)\n"
            "```\n\n"
            f"This code block is generated by the {provider} simulator to show code highlight rendering."
        )

    # 5. Default contextual reply
    topic = prompt.strip()
    if len(topic) > 40:
        topic = topic[:37] + "..."
    return (
        f"You queried: '{topic}'. This is a simulated response from {provider.upper()}. "
        f"In production, InferRoute's routing engine would analyze this query, check if the warm KV cache "
        f"resides on any active backend, and dispatch it to the most cost-efficient and latency-compliant node. "
        f"Currently, simulation mode is active, bypassing all commercial API fees."
    )
